version: "3"

networks:
  amnetv6:
    name: amnetv6
    external: true

services:
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 9117:9117
    volumes:
      - /share/homes/fitz/docker/jackett:/config
    restart: unless-stopped
    networks:
      - amnetv6

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - amnetv6

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 7878:7878
    volumes:
      - /share/homes/fitz/docker/radarr:/config
      - /share/Media:/media
      - /share/Media_Tmp:/media_tmp
    restart: unless-stopped
    networks:
      - amnetv6

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 8987:8989
    volumes:
      - /share/homes/fitz/docker/sonarr:/config
      - /share/Media:/media
      - /share/Media_Tmp:/media_tmp
    restart: unless-stopped
    networks:
      - amnetv6

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /share/homes/fitz/docker/chinesesubfinder/config:/config
      - /share/homes/fitz/docker/chinesesubfinder/browser:/root/.cache/rod/browser
      - /share/Media:/media
    environment:
      - PUID=1000
      - PGID=100
      - PERMS=false
      - TZ=Asia/Shanghai
      - UMASK=002
    restart: unless-stopped
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035
      # - 19037:19037  # webui
    logging:
        driver: "json-file"
        options:
          max-size: "100m"
    networks:
      - amnetv6

  qbittorrent:
    container_name: qbittorrent
    image: johngong/qbittorrent:latest
    environment:
      - QB_WEBUI_PORT=8989
      - QB_EE_BIN=false
      - QB_TRACKERS_UPDATE_AUTO=true
      - PUID=1000
      - PGID=100
      - UMASK=000
    ports:
      - 6882:6881
      - 6882:6881/udp
      - 8989:8989
    volumes:
      - /share/homes/fitz/docker/qbittorrent:/config
      - /share/homes/fitz/docker/qbittorrent_vuetorrent:/vuetorrent
      - /share/Media:/media
      - /share/Media_Tmp:/media_tmp
    restart: unless-stopped
    networks:
      - amnetv6
    
  jellyfin:
    container_name: jellyfin
    image: nyanmisaka/jellyfin:latest
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=192.168.12.10
    volumes:
      - /share/homes/fitz/docker/jellyfin:/config
      - /share/Media:/media
    ports:
      - 8097:8096
      - 8920:8920 # HTTPS port
      - 7359:7359/udp
      - 1901:1900/udp
    restart: unless-stopped
    networks:
      - amnetv6
    # privileged: true
    # command:
    #   - sh
    #   - -c
    #   - |
    #       chmod -R 777 /dev/dri/renderD128
    #       chmod -R 777 /dev/dri/card0
    #       bash
    # tty: true
    # stdin_open: true

  # emby:
  #   container_name: emby
  #   image: lscr.io/linuxserver/emby:latest
  #   environment:
  #     - PUID=1000
  #     - PGID=100
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - /share/homes/fitz/docker/emby:/config
  #     - /share/Media:/media
  #   ports:
  #     - 8096:8096
  #   restart: unless-stopped
  #   networks:
  #     - amnetv6

  qbit-auto-limit:
    container_name: qbit-auto-limit
    image: xiaoyi510/qbit-auto-limit:v0.0.5
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/homes/fitz/docker/qbit-auto-limit:/app/conf
    restart: unless-stopped
    networks:
      - amnetv6

  xarr-notify:
    container_name: xarr-notify
    image: xiaoyi510/xarr-notify:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/homes/fitz/docker/xarr-notify:/app/conf
      - /share/homes/fitz/docker/radarr/MediaCover:/app/images/radarr
      - /share/homes/fitz/docker/sonarr/MediaCover:/app/images/sonarr
    ports:
      - 8085:8085
    restart: unless-stopped
    networks:
      - amnetv6

  # busybox:
  #   image: busybox:latest
  #   container_name: busybox
  #   restart: unless-stopped
  #   tty: true
  #   environment:
  #     - PUID=1000
  #     - PGID=100
  #     - TZ=Asia/Shanghai
  #   networks:
  #     - amnetv6

  # nastools:
  #   image: jxxghp/nas-tools:latest
  #   container_name: nastools
  #   hostname: nastools
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /share/homes/fitz/docker/nastools:/config
  #     - /share/Media:/media
  #     - /share/Media_Tmp:/media_tmp
  #   environment:
  #     - PUID=1000
  #     - PGID=100
  #     - TZ=Asia/Shanghai
  #     - UMASK=002
  #   restart: unless-stopped
  #   networks:
  #     - amnetv6
