version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/homes/fitz/docker/heimdall:/config
    ports:
      - 8080:80
      - 4443:443
    restart: unless-stopped