services:

  # main service
  talebook:
    restart: always
    image: poxenstudio/talebook:latest
    volumes:
      - /share/homes/fitz/docker/talebook:/data
    ports:
      - "3000:80"
      - "3443:443"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    restart: always
    image: ghcr.io/cxfksword/douban-api-rs
