version: '3'

services:
  watchtower:
    name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      - --cleanup
      - $(cat /share/homes/fitz/docker/watchtower.list)
      - --schedule "0 0 1 * * *"