version: '2'

volumes:
  nextcloud:
  # db:

services:
  # db:
  #   image: mariadb
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
  #   restart: always
  #   volumes:
  #     - /mnt/nas_data/docker/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=nextcloud
  #     - MYSQL_PASSWORD=nextcloud
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud

  app:
    image: fitz07/nextcloud_plus
    ports:
      - 8080:80
    # links:
    #   - db
    # volumes:
    #   - /mnt/nas_data/docker/nextcloud:/var/www/html
    restart: always